export const reduxConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",

  LOGOUT: "USERS_LOGOUT",

  ORDER_DELIVERY_TYPE: "ORDER_DELIVERY_TYPE",

  TYPEAHEAD_OUTPUT: "TYPEAHEAD_OUTPUT",
  RESTAURANT_LIST: "RESTAURANT_LIST",
  FOOD_FILTER: "FOOD_FILTER",
  CUSTOMER_LOCATION: "CUSTOMER_LOCATION",
  TYPEAHEAD_SELECTED: "TYPEAHEAD_SELECTED",

  ADD_DISH_MODAL_SHOW: "ADD_DISH_MODAL_SHOW",
};
